// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuHkRzpgXjWAcHkaIJliOqyWHw7McxVA0',
    appId: '1:676982091817:web:66f4d69bd74f186d856c38',
    messagingSenderId: '676982091817',
    projectId: 'pockettutor-f9bfb',
    authDomain: 'pockettutor-f9bfb.firebaseapp.com',
    databaseURL: 'https://pockettutor-f9bfb-default-rtdb.firebaseio.com',
    storageBucket: 'pockettutor-f9bfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2lAbEgwcFGEr_85aTkX0MJyWjrN2VD-c',
    appId: '1:676982091817:android:1602a75040cf922c856c38',
    messagingSenderId: '676982091817',
    projectId: 'pockettutor-f9bfb',
    databaseURL: 'https://pockettutor-f9bfb-default-rtdb.firebaseio.com',
    storageBucket: 'pockettutor-f9bfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBReBU0pi4rACXl3GNR7GZCWM4GH1IQbI',
    appId: '1:676982091817:ios:d905f192af3d0876856c38',
    messagingSenderId: '676982091817',
    projectId: 'pockettutor-f9bfb',
    databaseURL: 'https://pockettutor-f9bfb-default-rtdb.firebaseio.com',
    storageBucket: 'pockettutor-f9bfb.firebasestorage.app',
    androidClientId: '676982091817-nrcj93feruloh0lqjmfflvaj6sc3l2ua.apps.googleusercontent.com',
    iosClientId: '676982091817-t9rkoemqkl05a1qje2mquvgek5udu6a5.apps.googleusercontent.com',
    iosBundleId: 'com.harshit.pockettutor',
  );
}
